#!/usr/bin/env bash
# Walk the user through Grafana Cloud token creation and write .env.
#
# Prerequisite: a Grafana Cloud account (free tier is fine).
#
# We collect:
#   GRAFANA_CLOUD_STACK_URL          your stack URL  (e.g. https://my-org.grafana.net)
#   GRAFANA_CLOUD_OTLP_ENDPOINT      OTLP gateway URL
#   GRAFANA_CLOUD_OTLP_INSTANCE_ID   numeric instance ID
#   GRAFANA_CLOUD_OTLP_API_TOKEN     access-policy token (metrics:write, logs:write)
#   GRAFANA_CLOUD_API_TOKEN          service-account token (dashboards:write, datasources:read)
#
# Re-running with an existing .env preserves prior values as defaults.

set -euo pipefail

# shellcheck disable=SC1091
. "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"

log_step "Step 2/5: Onboard Grafana Cloud token"

ENV_FILE="$CLAUDE_PLUGIN_ROOT/.env"

# Pre-fill from existing .env if present.
if [ -f "$ENV_FILE" ]; then
  load_env "$ENV_FILE"
  log_dim "Existing .env detected — values shown as defaults."
fi

cat >&2 <<EOF

This step writes a token-bearing .env file at:
  ${ENV_FILE}

It is gitignored and chmod 600. Never commit it. The setup wizard rotates the
token by re-running this step or you can edit .env manually.

Two tokens are needed (different scopes — keep them separate):
  1) OTLP push token   — Alloy → Grafana Cloud (metrics:write, logs:write)
  2) HTTP API token    — skills → Grafana Cloud (dashboards:write, datasources:read)

You can find both endpoints under your Grafana Cloud stack:
  • https://grafana.com/orgs/<your-org>/stacks  →  pick stack
  • "Send Data" → "OpenTelemetry" tile shows OTLP endpoint + instance ID
  • "Access Policies" lets you mint a token with the right scopes

EOF

if confirm "Open the Grafana Cloud token UI in your browser now?" "y"; then
  url="https://grafana.com/profile/org#access-policies"
  if command -v xdg-open >/dev/null 2>&1; then
    run_or_print xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v open >/dev/null 2>&1; then
    run_or_print open "$url" >/dev/null 2>&1 || true
  else
    log_info "Open this URL: $url"
  fi
fi

# Collect values.
log_info "Paste the values from your Grafana Cloud stack."

stack_url="$(prompt_value 'Stack URL (e.g. https://my-org.grafana.net)' "${GRAFANA_CLOUD_STACK_URL:-}")"
otlp_endpoint="$(prompt_value 'OTLP gateway endpoint' "${GRAFANA_CLOUD_OTLP_ENDPOINT:-}")"
instance_id="$(prompt_value 'OTLP instance ID (numeric)' "${GRAFANA_CLOUD_OTLP_INSTANCE_ID:-}")"
otlp_token="$(prompt_secret 'OTLP push token (glc_... or glsa_...)')"
api_token="$(prompt_secret 'HTTP API token for skills (glsa_...)')"

# Validate non-empty.
for var in stack_url otlp_endpoint instance_id otlp_token api_token; do
  if [ -z "${!var}" ]; then
    die "Missing value for $var. Re-run /grafana-setup."
  fi
done

# Validate URL shape.
case "$stack_url" in
  https://*.grafana.net|https://*.grafana.net/) ;;
  *) log_warn "Stack URL should look like https://<your>.grafana.net — continuing anyway." ;;
esac
case "$otlp_endpoint" in
  https://*) ;;
  *) die "OTLP endpoint must be https://" ;;
esac

# Smoke-test the API token by hitting /api/datasources.
if command -v curl >/dev/null 2>&1; then
  log_info "Verifying HTTP API token against $stack_url ..."
  http_code="$(curl -fsS -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer $api_token" \
    "${stack_url%/}/api/datasources" 2>/dev/null || echo "000")"
  case "$http_code" in
    200) log_ok "HTTP API token works." ;;
    401|403) die "HTTP API token rejected ($http_code). Check the token has datasources:read." ;;
    000) log_warn "Could not reach $stack_url. Continuing — verify connectivity later." ;;
    *) log_warn "Unexpected response from /api/datasources: $http_code. Continuing." ;;
  esac
fi

# Write atomically with chmod 600.
tmp="$(mktemp "$CLAUDE_PLUGIN_ROOT/.env.XXXXXX")"
chmod 0600 "$tmp"
cat >"$tmp" <<EOF
# Generated by claude-grafana /grafana-setup on $(date -Iseconds)
# DO NOT COMMIT. .env is gitignored.

GRAFANA_CLOUD_STACK_URL=$stack_url
GRAFANA_CLOUD_OTLP_ENDPOINT=$otlp_endpoint
GRAFANA_CLOUD_OTLP_INSTANCE_ID=$instance_id
GRAFANA_CLOUD_OTLP_API_TOKEN=$otlp_token

GRAFANA_CLOUD_API_TOKEN=$api_token

GRAFANA_CLOUD_PROM_DATASOURCE_UID=
GRAFANA_CLOUD_LOKI_DATASOURCE_UID=
GRAFANA_CLOUD_DASHBOARD_FOLDER_UID=
EOF

if [ "$DRY_RUN" = "1" ]; then
  log_dim "  [dry-run] would write $ENV_FILE (chmod 600)"
  rm -f "$tmp"
else
  mv "$tmp" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
  log_ok "Wrote $ENV_FILE (chmod 600)"
fi
