#!/usr/bin/env bash
# Install or merge the claude.alloy module into the running Alloy config.
#
# Strategy depends on classification of the existing config (alloy_config_detect.sh):
#
#   missing   → write fresh config.alloy that just imports claude.alloy
#   empty     → same as missing
#   has-claude → re-write claude.alloy (idempotent), do not touch main config
#   has-otlp  → ABORT with a clear error: would conflict on 127.0.0.1:4317
#   has-other → ask user: merge / replace / skip
#   unreadable → ABORT with permission hint
#
# Always:
#   - back up main config + claude.alloy + systemd drop-in to .pre-claude-grafana.bak
#   - render claude.alloy from claude.alloy.tmpl with VERSION substituted
#   - install systemd drop-in pointing to /etc/alloy/claude.env
#   - alloy fmt + alloy run --check before reload
#   - rollback on validation failure
#
# Honors --force to skip the merge prompt and always merge.

set -euo pipefail

# shellcheck disable=SC1091
. "$(cd "$(dirname "$0")" && pwd)/lib/common.sh"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
  esac
done

log_step "Step 3/5: Configure Alloy"

require_cmd alloy

ENV_FILE="$CLAUDE_PLUGIN_ROOT/.env"
[ -f "$ENV_FILE" ] || die ".env missing — run scripts/02-onboard-token.sh first."
load_env "$ENV_FILE"
require_env GRAFANA_CLOUD_OTLP_ENDPOINT
require_env GRAFANA_CLOUD_OTLP_INSTANCE_ID
require_env GRAFANA_CLOUD_OTLP_API_TOKEN

MAIN_CFG="$(alloy_config_path)"
MOD_CFG="$(alloy_module_path)"
ENV_DROPIN="$(alloy_envfile_path)"
SD_DROPIN="/etc/systemd/system/alloy.service.d/claude.conf"
TMPL="$CLAUDE_PLUGIN_ROOT/alloy/claude.alloy.tmpl"

VERSION="$(json_get "$CLAUDE_PLUGIN_ROOT/.claude-plugin/plugin.json" '.version' || echo 'unknown')"

log_dim "Main config: $MAIN_CFG"
log_dim "Module:      $MOD_CFG"
log_dim "Env file:    $ENV_DROPIN"
log_dim "SD dropin:   $SD_DROPIN (linux-only)"

classification="$("$CLAUDE_PLUGIN_ROOT/scripts/alloy_config_detect.sh" "$MAIN_CFG")"
log_info "Existing config classification: $classification"

choice=""
case "$classification" in
  missing|empty)
    choice="replace"
    ;;
  has-claude)
    log_ok "Existing config already imports claude.alloy. Re-rendering module only."
    choice="module-only"
    ;;
  has-otlp)
    die "Existing config declares an otelcol.receiver.otlp on 127.0.0.1:4317. Would conflict.
    Either remove the existing receiver, or change its endpoint, then re-run."
    ;;
  has-other)
    if [ "$FORCE" -eq 1 ]; then
      choice="merge"
    else
      cat >&2 <<EOF

Your existing $MAIN_CFG has unrelated Alloy components.
Three ways to add the claude pipeline:

  merge   - drop a separate claude.alloy module and add ONE import.file line
            to your main config. NON-DESTRUCTIVE. Recommended.
  replace - back up your main config and replace it with a claude-only one.
            DESTRUCTIVE. Existing pipelines will stop running.
  skip    - print the snippet and let you paste it manually.

EOF
      choice="$(prompt_choice 'Choose:' 'merge' merge replace skip)"
    fi
    ;;
  unreadable)
    die "Cannot read $MAIN_CFG. Re-run with sudo or fix permissions."
    ;;
  *)
    die "Unknown classification: $classification"
    ;;
esac

# ── Render claude.alloy module ────────────────────────────────────────────
render_module() {
  local out="$1"
  local rendered
  rendered="$(sed "s/{{VERSION}}/$VERSION/g" "$TMPL")"
  log_info "Writing module: $out"
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would write $out:"
    printf '%s\n' "$rendered" | sed 's/^/    /' >&2
    return 0
  fi
  if alloy_needs_sudo; then
    printf '%s\n' "$rendered" | maybe_sudo tee "$out" >/dev/null
    maybe_sudo chmod 0644 "$out"
  else
    ensure_dir "$(dirname "$out")"
    printf '%s\n' "$rendered" >"$out"
    chmod 0644 "$out"
  fi
}

# ── Render claude.env (env file for systemd drop-in) ──────────────────────
render_envfile() {
  local out="$1"
  local content
  content="$(cat <<EOF
# Generated by claude-grafana on $(date -Iseconds). chmod 600.
GRAFANA_CLOUD_OTLP_ENDPOINT=$GRAFANA_CLOUD_OTLP_ENDPOINT
GRAFANA_CLOUD_OTLP_INSTANCE_ID=$GRAFANA_CLOUD_OTLP_INSTANCE_ID
GRAFANA_CLOUD_OTLP_API_TOKEN=$GRAFANA_CLOUD_OTLP_API_TOKEN
EOF
)"
  log_info "Writing env file: $out"
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would write $out (chmod 600)"
    return 0
  fi
  if alloy_needs_sudo; then
    printf '%s\n' "$content" | maybe_sudo tee "$out" >/dev/null
    maybe_sudo chmod 0600 "$out"
  else
    ensure_dir "$(dirname "$out")"
    printf '%s\n' "$content" >"$out"
    chmod 0600 "$out"
  fi
}

# ── Render systemd drop-in ────────────────────────────────────────────────
render_systemd_dropin() {
  if ! command -v systemctl >/dev/null 2>&1; then
    log_dim "systemctl not present — skipping systemd drop-in."
    return 0
  fi
  local out="$1"
  local content
  content="$(cat <<EOF
# Generated by claude-grafana. Adds env file for the OTLP exporter.
[Service]
EnvironmentFile=$ENV_DROPIN
EOF
)"
  log_info "Writing systemd drop-in: $out"
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would write $out and run systemctl daemon-reload"
    return 0
  fi
  maybe_sudo mkdir -p "$(dirname "$out")"
  printf '%s\n' "$content" | maybe_sudo tee "$out" >/dev/null
  maybe_sudo systemctl daemon-reload
}

# ── Main config write strategies ──────────────────────────────────────────
write_replace_main() {
  backup_file "$MAIN_CFG"
  local content
  content="$(cat <<EOF
// Generated by claude-grafana on $(date -Iseconds).
// To add other Alloy pipelines, append components below the import.file.

import.file "claude" {
  filename = "$MOD_CFG"
}
EOF
)"
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would write $MAIN_CFG"
    return 0
  fi
  if alloy_needs_sudo; then
    printf '%s\n' "$content" | maybe_sudo tee "$MAIN_CFG" >/dev/null
    maybe_sudo chmod 0644 "$MAIN_CFG"
  else
    ensure_dir "$(dirname "$MAIN_CFG")"
    printf '%s\n' "$content" >"$MAIN_CFG"
    chmod 0644 "$MAIN_CFG"
  fi
  log_ok "Replaced $MAIN_CFG with claude-only config."
}

write_merge_main() {
  backup_file "$MAIN_CFG"
  local marker="// claude-grafana: import managed by /grafana-setup"
  local import_line="import.file \"claude\" { filename = \"$MOD_CFG\" }"
  if grep -q "$marker" "$MAIN_CFG" 2>/dev/null; then
    log_dim "Import line already present. Idempotent — no main-config edit."
    return 0
  fi
  log_info "Appending import.file line to $MAIN_CFG"
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would append:"
    log_dim "    $marker"
    log_dim "    $import_line"
    return 0
  fi
  if alloy_needs_sudo; then
    printf '\n%s\n%s\n' "$marker" "$import_line" | maybe_sudo tee -a "$MAIN_CFG" >/dev/null
  else
    printf '\n%s\n%s\n' "$marker" "$import_line" >>"$MAIN_CFG"
  fi
}

print_skip_snippet() {
  cat >&2 <<EOF

Paste the following into $MAIN_CFG (or any imported module):

──────────────────────────────────────────────────────────────────────
$(cat "$CLAUDE_PLUGIN_ROOT/alloy/claude-merge-snippet.alloy")
──────────────────────────────────────────────────────────────────────

Then ensure $ENV_DROPIN is sourced by the Alloy service:
  $SD_DROPIN  with EnvironmentFile=$ENV_DROPIN

Re-run /grafana-status when done.
EOF
}

# ── Validate ──────────────────────────────────────────────────────────────
validate_alloy() {
  log_info "Validating Alloy config..."
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would run: alloy fmt $MOD_CFG && alloy fmt $MAIN_CFG"
    return 0
  fi
  # `alloy fmt --test` exits non-zero on parse errors. Use it as our static check.
  if ! alloy fmt --test "$MOD_CFG" >/dev/null 2>&1; then
    # Older alloy versions don't accept --test; fall back to plain fmt.
    if ! alloy fmt "$MOD_CFG" >/dev/null 2>&1; then
      die "alloy fmt rejected $MOD_CFG."
    fi
  fi
  if ! maybe_sudo alloy fmt --test "$MAIN_CFG" >/dev/null 2>&1; then
    if ! maybe_sudo alloy fmt "$MAIN_CFG" >/dev/null 2>&1; then
      die "alloy fmt rejected $MAIN_CFG."
    fi
  fi
  log_ok "Alloy config parses cleanly."
}

reload_alloy() {
  if ! command -v systemctl >/dev/null 2>&1; then
    log_warn "systemctl not present. Reload Alloy manually."
    return 0
  fi
  log_info "Reloading alloy.service ..."
  if [ "$DRY_RUN" = "1" ]; then
    log_dim "  [dry-run] would run: systemctl reload-or-restart alloy"
    return 0
  fi
  maybe_sudo systemctl reload-or-restart alloy
  sleep 1
  if maybe_sudo systemctl is-active --quiet alloy; then
    log_ok "alloy.service is active."
  else
    log_err "alloy.service failed to start. Recent logs:"
    maybe_sudo journalctl -u alloy --no-pager -n 30 >&2 || true
    die "Rolling back via the .pre-claude-grafana.bak files."
  fi
}

# ── Execute ───────────────────────────────────────────────────────────────
case "$choice" in
  replace)
    backup_file "$MOD_CFG"
    render_module "$MOD_CFG"
    render_envfile "$ENV_DROPIN"
    render_systemd_dropin "$SD_DROPIN"
    write_replace_main
    validate_alloy
    reload_alloy
    ;;
  merge)
    backup_file "$MOD_CFG"
    render_module "$MOD_CFG"
    render_envfile "$ENV_DROPIN"
    render_systemd_dropin "$SD_DROPIN"
    write_merge_main
    validate_alloy
    reload_alloy
    ;;
  module-only)
    render_module "$MOD_CFG"
    render_envfile "$ENV_DROPIN"
    render_systemd_dropin "$SD_DROPIN"
    validate_alloy
    reload_alloy
    ;;
  skip)
    render_envfile "$ENV_DROPIN"
    print_skip_snippet
    log_warn "Manual paste required. /grafana-status will show red until done."
    ;;
  *)
    die "Internal error: unknown choice $choice"
    ;;
esac

log_ok "Step 3/5 complete."
